# Generated by Django 4.1.5 on 2023-02-13 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0002_funcionario_departamento_funcionario_empresa_and_more'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pertence',
            field=models.ForeignKey(blank=True, null=True, 
                                    on_delete=django.db.models.deletion.SET_NULL, 
                                    to='Funcionarios.funcionario'),
        ),
    ]
